### ISSUE TITLE
How about updating to Rails 5 ?

### ISSUE THREAD

**Issue by Adagio-cantabile** [Simcookies/Micro-ME#2]
It'll be a good way to learn Rails 5.

**Comment by Simcookies** [comment]
I think this project was too small to upgrade. We can make a new idea to improve programming skill, not only Web Developing, but also other areas. Such as Machine Learning, GUI, Mobile Device or even Embaded Development. How do think about it?

**Comment by Adagio-cantabile** [comment]
We can also upgrade Ruby to 2.4.0 and use ActionCable in message notifier. It won't be that easy.

**Comment by Simcookies** [comment]
Uhm, sounds not bad. Do you have some plans?
